query countTypes {
  jobsConnection {
    groupBy {
        JobType {
        key,
        connection {
            aggregate {
            count
            }
        }
        }
    }

    aggregate {
        count
    }
  }
}