query job ( $jobId: ID! ) {
    job( id: $jobId ) {
    id
    title
    description
    Published
    JobType
    Salary
    ApplyEmail
    ApplyWebsite
    company {
      id
      Title
      Address
      Website
      Logo {
        url
      }
    }
    jobareas {
      id
      AreaName
    }
    languages {
      id
      LangName
    }
    createdAt
    updatedAt
  }
}